apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjobscaleup
  namespace: default
spec:
  schedule: "0 8 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjobscaleup
            image: cronjobscaleup:latest
            args:
              - "kubectl scale deployment.v1.apps/zenith-service --replicas=3"
            env:
            - name: "SERVICE_ACCOUNT_KEY"
              valueFrom:
                secretKeyRef:
                  key: "SERVICE_ACCOUNT_KEY"
                  name: "scale-job-secret"