name: cronjobscale

on:
  workflow_dispatch:


# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: ctonjobscale:${{ github.sha }}
  working-directory: /

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name : Configure las credenciales de AWS 
      uses : aws-actions/configure-aws-credentials@v1 
      with: 
         aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region : us-east-2
           
           
